'use client';
import { Center, Flex, Heading, Text, VStack } from '@chakra-ui/react';
import React from 'react';

function AboutUs() {
  return (
    <Flex justifyContent="center" alignItems="center" mt={5}>
      <VStack w="full" maxW="lg">
        <Center>
          <Heading variant="h6"> We are here for you </Heading>
        </Center>
        <Center>
          <Text textAlign="justify">
            Welcome to our e-commerce store! We are a team of passionate
            individuals who are dedicated to providing you with the best
            possible online shopping experience. Our store offers a wide range
            of products that have been carefully curated to cater to your unique
            needs.
            <br />
            Our mission is to make online shopping simple and convenient for
            you. We understand that shopping can be a daunting task, especially
            when it comes to buying products online. That's why we have designed
            our website to be user-friendly, making it easy for you to find what
            you're looking for.
            <br />
            We take pride in the quality of our products and are committed to
            providing you with only the best. We work with trusted suppliers and
            manufacturers to ensure that our products meet the highest
            standards. Our team carefully inspects each product before it is
            shipped to ensure that it meets our quality standards.
            <br />
            We value your feedback and take it seriously. If you have any
            suggestions or comments, we encourage you to share them with us. We
            are always looking for ways to improve and provide a better shopping
            experience for you.
            <br />
            Thank you for choosing our e-commerce store for your online shopping
            needs. We appreciate your business and look forward to serving you!
            <br />
            <br />
            <br />
            <br />
            *** This is a test website. Above text is generated by ChatGPT
          </Text>
        </Center>
      </VStack>
    </Flex>
  );
}

export default AboutUs;
